services:
  db:
    image: pg18-trixie
    environment:
      POSTGRES_USER: rave-digital-user
      POSTGRES_PASSWORD: rave-digital-pass
      POSTGRES_DB: rave-digital
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    image: redis:8.8.0-alpine
#    environment:
#      REDIS_USERNAME: rave-digital-user
#      REDIS_PASSWORD: rave-digital-user
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama:0.32.2
    ports:
      - "11434:11434"
    volumes:
      - ./model_files:/model_files
    tty: true  # not sure why
    restart: unless-stopped