services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rave-digital-app:local
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis


  db:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: rave-digital-user
      POSTGRES_PASSWORD: rave-digital-pass
      POSTGRES_DB: rave-digital
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "127.0.0.1:5435:5432"

  redis:
    image: redis:8.8.0-alpine
#    environment:
#      REDIS_USERNAME: rave-digital-user
#      REDIS_PASSWORD: rave-digital-user
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama:0.32.2
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      OLLAMA_KEEP_ALIVE: 30
      # maximum number of models that can be loaded concurrently provided they fit in available memory.
      #
      OLLAMA_MAX_LOADED_MODELS: 2
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


volumes:
  dbdata:
  redis-data:
  ollama-models: